#
# @file  appveyor.yml
# @brief AppVeyor continuous integration config file. Build and run unit tests
#        on Windows with Visual Studio.
#
version: 1.0.{build}

image: Visual Studio 2022

install:
  - cd c:\tools\vcpkg\
  - git pull
  - .\bootstrap-vcpkg.bat -disableMetrics
  - vcpkg install benchmark:x64-windows boost-asio:x64-windows boost-test:x64-windows
  - cd %APPVEYOR_BUILD_FOLDER%

cache:
  - c:\tools\vcpkg\installed\

branches:
  only:
    - main

configuration:
  - Release

platform:
  - x64

before_build:
  - cmd: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake

build:
  verbosity: normal

test_script:
  - cmd: python test\mock_sdk_server.py build\test\%CONFIGURATION%\shadowmocap_test.exe
