#
# @file  appveyor.yml
# @brief AppVeyor continuous integration config file. Build and run unit tests
#        on Windows with Visual Studio.
#
version: 1.0.{build}

image: Visual Studio 2022

install:
  - git submodule init
  - git submodule update

branches:
  only:
    - main

configuration: Release

platform:
  - x64
  - Win32

build:
  verbosity: minimal

test_script:
  - cmd: python test\mock_sdk_server.py build\bin\%PLATFORM%\%CONFIGURATION%\test_shadowmocap.exe