name: shadowmocap-sdk-cpp CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: make
      run: make
    - name: make test
      run: make test