name: shadowmocap-sdk-cpp CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: make
      run: make
      working-directory: build
    - name: make test
      run: make test
      working-directory: build