name: shadowmocap-sdk-cpp CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Compile unit test app
      run: make
      working-directory: build
      env:
        CXX: clang++
    - name: Run unit tests
      run: make test
      working-directory: build
      env:
        CXX: clang++